### ISSUE TITLE
Break down forms into partials

### ISSUE THREAD

**Issue by heidar** [ministryofjustice/laa-apply-for-legal-aid-provider-frontend#54]
The forms on the project could do with some DRYing up. For example, the client details form and the email form could share a common container form.

In addition, the individual form fields could be broken out into their own partials to some extent, such as the date question. When this is done we should double check that what we have done matches what GDS expects.

**Comment by willc-work** [comment]
this has been done in AP-153

**Comment by heidar** [comment]
:+1: closing
